name: stories
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  pocketbase: ^0.22.0
  shared_preferences: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
