name: stories
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  file_picker: ^9.2.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.4.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  path: ^1.9.1
  pocketbase: ^0.22.0
  shared_preferences: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/ # Include entire fonts directory

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-VariableFont_opsz,wdth,wght.ttf
          weight: 400 # Default weight for variable font

    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
          weight: 400

    - family: CrimsonPro
      fonts:
        - asset: assets/fonts/CrimsonPro-VariableFont_wght.ttf
          weight: 400

    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond-VariableFont_wght.ttf
          weight: 400