// Mocks generated by Mockito 5.4.5 from annotations
// in stories/test/screens/edit_book_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:http/http.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;
import 'package:pocketbase/src/auth_store.dart' as _i2;
import 'package:pocketbase/src/client.dart' as _i15;
import 'package:pocketbase/src/dtos/auth_methods_list.dart' as _i17;
import 'package:pocketbase/src/dtos/jsonable.dart' as _i20;
import 'package:pocketbase/src/dtos/otp_response.dart' as _i19;
import 'package:pocketbase/src/dtos/record_auth.dart' as _i18;
import 'package:pocketbase/src/dtos/record_model.dart' as _i16;
import 'package:pocketbase/src/dtos/result_list.dart' as _i21;
import 'package:pocketbase/src/services/backup_service.dart' as _i9;
import 'package:pocketbase/src/services/batch_service.dart' as _i13;
import 'package:pocketbase/src/services/collection_service.dart' as _i3;
import 'package:pocketbase/src/services/cron_service.dart' as _i10;
import 'package:pocketbase/src/services/file_service.dart' as _i4;
import 'package:pocketbase/src/services/health_service.dart' as _i8;
import 'package:pocketbase/src/services/log_service.dart' as _i7;
import 'package:pocketbase/src/services/realtime_service.dart' as _i5;
import 'package:pocketbase/src/services/record_service.dart' as _i12;
import 'package:pocketbase/src/services/settings_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthStore_0 extends _i1.SmartFake implements _i2.AuthStore {
  _FakeAuthStore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionService_1 extends _i1.SmartFake
    implements _i3.CollectionService {
  _FakeCollectionService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileService_2 extends _i1.SmartFake implements _i4.FileService {
  _FakeFileService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeService_3 extends _i1.SmartFake
    implements _i5.RealtimeService {
  _FakeRealtimeService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsService_4 extends _i1.SmartFake
    implements _i6.SettingsService {
  _FakeSettingsService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogService_5 extends _i1.SmartFake implements _i7.LogService {
  _FakeLogService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthService_6 extends _i1.SmartFake implements _i8.HealthService {
  _FakeHealthService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackupService_7 extends _i1.SmartFake implements _i9.BackupService {
  _FakeBackupService_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCronService_8 extends _i1.SmartFake implements _i10.CronService {
  _FakeCronService_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_9 extends _i1.SmartFake implements _i11.Client {
  _FakeClient_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecordService_10 extends _i1.SmartFake
    implements _i12.RecordService {
  _FakeRecordService_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_11 extends _i1.SmartFake implements Uri {
  _FakeUri_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchService_12 extends _i1.SmartFake implements _i13.BatchService {
  _FakeBatchService_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_13<T1> extends _i1.SmartFake implements _i14.Future<T1> {
  _FakeFuture_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePocketBase_14 extends _i1.SmartFake implements _i15.PocketBase {
  _FakePocketBase_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecordModel_15 extends _i1.SmartFake implements _i16.RecordModel {
  _FakeRecordModel_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthMethodsList_16 extends _i1.SmartFake
    implements _i17.AuthMethodsList {
  _FakeAuthMethodsList_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecordAuth_17 extends _i1.SmartFake implements _i18.RecordAuth {
  _FakeRecordAuth_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOTPResponse_18 extends _i1.SmartFake implements _i19.OTPResponse {
  _FakeOTPResponse_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResultList_19<M extends _i20.Jsonable> extends _i1.SmartFake
    implements _i21.ResultList<M> {
  _FakeResultList_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PocketBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPocketBase extends _i1.Mock implements _i15.PocketBase {
  MockPocketBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseURL =>
      (super.noSuchMethod(
            Invocation.getter(#baseURL),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#baseURL),
            ),
          )
          as String);

  @override
  set baseURL(String? _baseURL) => super.noSuchMethod(
    Invocation.setter(#baseURL, _baseURL),
    returnValueForMissingStub: null,
  );

  @override
  String get lang =>
      (super.noSuchMethod(
            Invocation.getter(#lang),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#lang),
            ),
          )
          as String);

  @override
  set lang(String? _lang) => super.noSuchMethod(
    Invocation.setter(#lang, _lang),
    returnValueForMissingStub: null,
  );

  @override
  _i2.AuthStore get authStore =>
      (super.noSuchMethod(
            Invocation.getter(#authStore),
            returnValue: _FakeAuthStore_0(this, Invocation.getter(#authStore)),
          )
          as _i2.AuthStore);

  @override
  set authStore(_i2.AuthStore? _authStore) => super.noSuchMethod(
    Invocation.setter(#authStore, _authStore),
    returnValueForMissingStub: null,
  );

  @override
  _i3.CollectionService get collections =>
      (super.noSuchMethod(
            Invocation.getter(#collections),
            returnValue: _FakeCollectionService_1(
              this,
              Invocation.getter(#collections),
            ),
          )
          as _i3.CollectionService);

  @override
  set collections(_i3.CollectionService? _collections) => super.noSuchMethod(
    Invocation.setter(#collections, _collections),
    returnValueForMissingStub: null,
  );

  @override
  _i4.FileService get files =>
      (super.noSuchMethod(
            Invocation.getter(#files),
            returnValue: _FakeFileService_2(this, Invocation.getter(#files)),
          )
          as _i4.FileService);

  @override
  set files(_i4.FileService? _files) => super.noSuchMethod(
    Invocation.setter(#files, _files),
    returnValueForMissingStub: null,
  );

  @override
  _i5.RealtimeService get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeService_3(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i5.RealtimeService);

  @override
  set realtime(_i5.RealtimeService? _realtime) => super.noSuchMethod(
    Invocation.setter(#realtime, _realtime),
    returnValueForMissingStub: null,
  );

  @override
  _i6.SettingsService get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettingsService_4(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i6.SettingsService);

  @override
  set settings(_i6.SettingsService? _settings) => super.noSuchMethod(
    Invocation.setter(#settings, _settings),
    returnValueForMissingStub: null,
  );

  @override
  _i7.LogService get logs =>
      (super.noSuchMethod(
            Invocation.getter(#logs),
            returnValue: _FakeLogService_5(this, Invocation.getter(#logs)),
          )
          as _i7.LogService);

  @override
  set logs(_i7.LogService? _logs) => super.noSuchMethod(
    Invocation.setter(#logs, _logs),
    returnValueForMissingStub: null,
  );

  @override
  _i8.HealthService get health =>
      (super.noSuchMethod(
            Invocation.getter(#health),
            returnValue: _FakeHealthService_6(this, Invocation.getter(#health)),
          )
          as _i8.HealthService);

  @override
  set health(_i8.HealthService? _health) => super.noSuchMethod(
    Invocation.setter(#health, _health),
    returnValueForMissingStub: null,
  );

  @override
  _i9.BackupService get backups =>
      (super.noSuchMethod(
            Invocation.getter(#backups),
            returnValue: _FakeBackupService_7(
              this,
              Invocation.getter(#backups),
            ),
          )
          as _i9.BackupService);

  @override
  set backups(_i9.BackupService? _backups) => super.noSuchMethod(
    Invocation.setter(#backups, _backups),
    returnValueForMissingStub: null,
  );

  @override
  _i10.CronService get crons =>
      (super.noSuchMethod(
            Invocation.getter(#crons),
            returnValue: _FakeCronService_8(this, Invocation.getter(#crons)),
          )
          as _i10.CronService);

  @override
  set crons(_i10.CronService? _crons) => super.noSuchMethod(
    Invocation.setter(#crons, _crons),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Client Function() get httpClientFactory =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientFactory),
            returnValue:
                () =>
                    _FakeClient_9(this, Invocation.getter(#httpClientFactory)),
          )
          as _i11.Client Function());

  @override
  set httpClientFactory(_i11.Client Function()? _httpClientFactory) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientFactory, _httpClientFactory),
        returnValueForMissingStub: null,
      );

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  set baseUrl(String? v) => super.noSuchMethod(
    Invocation.setter(#baseUrl, v),
    returnValueForMissingStub: null,
  );

  @override
  _i12.RecordService get admins =>
      (super.noSuchMethod(
            Invocation.getter(#admins),
            returnValue: _FakeRecordService_10(
              this,
              Invocation.getter(#admins),
            ),
          )
          as _i12.RecordService);

  @override
  _i12.RecordService collection(String? collectionIdOrName) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionIdOrName]),
            returnValue: _FakeRecordService_10(
              this,
              Invocation.method(#collection, [collectionIdOrName]),
            ),
          )
          as _i12.RecordService);

  @override
  String filter(String? expr, [Map<String, dynamic>? query = const {}]) =>
      (super.noSuchMethod(
            Invocation.method(#filter, [expr, query]),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.method(#filter, [expr, query]),
            ),
          )
          as String);

  @override
  Uri getFileUrl(
    _i16.RecordModel? record,
    String? filename, {
    String? thumb,
    String? token,
    Map<String, dynamic>? query = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileUrl,
              [record, filename],
              {#thumb: thumb, #token: token, #query: query},
            ),
            returnValue: _FakeUri_11(
              this,
              Invocation.method(
                #getFileUrl,
                [record, filename],
                {#thumb: thumb, #token: token, #query: query},
              ),
            ),
          )
          as Uri);

  @override
  Uri buildUrl(
    String? path, [
    Map<String, dynamic>? queryParameters = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#buildUrl, [path, queryParameters]),
            returnValue: _FakeUri_11(
              this,
              Invocation.method(#buildUrl, [path, queryParameters]),
            ),
          )
          as Uri);

  @override
  Uri buildURL(
    String? path, [
    Map<String, dynamic>? queryParameters = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#buildURL, [path, queryParameters]),
            returnValue: _FakeUri_11(
              this,
              Invocation.method(#buildURL, [path, queryParameters]),
            ),
          )
          as Uri);

  @override
  _i13.BatchService createBatch() =>
      (super.noSuchMethod(
            Invocation.method(#createBatch, []),
            returnValue: _FakeBatchService_12(
              this,
              Invocation.method(#createBatch, []),
            ),
          )
          as _i13.BatchService);

  @override
  _i14.Future<T> send<T extends dynamic>(
    String? path, {
    String? method = 'GET',
    Map<String, String>? headers = const {},
    Map<String, dynamic>? query = const {},
    Map<String, dynamic>? body = const {},
    List<_i11.MultipartFile>? files = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #send,
              [path],
              {
                #method: method,
                #headers: headers,
                #query: query,
                #body: body,
                #files: files,
              },
            ),
            returnValue:
                _i22.ifNotNull(
                  _i22.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #send,
                      [path],
                      {
                        #method: method,
                        #headers: headers,
                        #query: query,
                        #body: body,
                        #files: files,
                      },
                    ),
                  ),
                  (T v) => _i14.Future<T>.value(v),
                ) ??
                _FakeFuture_13<T>(
                  this,
                  Invocation.method(
                    #send,
                    [path],
                    {
                      #method: method,
                      #headers: headers,
                      #query: query,
                      #body: body,
                      #files: files,
                    },
                  ),
                ),
          )
          as _i14.Future<T>);
}

/// A class which mocks [RecordService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordService extends _i1.Mock implements _i12.RecordService {
  MockRecordService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseCollectionPath =>
      (super.noSuchMethod(
            Invocation.getter(#baseCollectionPath),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#baseCollectionPath),
            ),
          )
          as String);

  @override
  String get baseCrudPath =>
      (super.noSuchMethod(
            Invocation.getter(#baseCrudPath),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#baseCrudPath),
            ),
          )
          as String);

  @override
  _i15.PocketBase get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakePocketBase_14(this, Invocation.getter(#client)),
          )
          as _i15.PocketBase);

  @override
  _i16.RecordModel itemFactoryFunc(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#itemFactoryFunc, [json]),
            returnValue: _FakeRecordModel_15(
              this,
              Invocation.method(#itemFactoryFunc, [json]),
            ),
          )
          as _i16.RecordModel);

  @override
  _i14.Future<_i5.UnsubscribeFunc> subscribe(
    String? topic,
    _i12.RecordSubscriptionFunc? callback, {
    String? expand,
    String? filter,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [topic, callback],
              {
                #expand: expand,
                #filter: filter,
                #fields: fields,
                #query: query,
                #headers: headers,
              },
            ),
            returnValue: _i14.Future<_i5.UnsubscribeFunc>.value(
              () => _i14.Future<void>.value(),
            ),
          )
          as _i14.Future<_i5.UnsubscribeFunc>);

  @override
  _i14.Future<void> unsubscribe([String? topic = '']) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [topic]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i16.RecordModel> update(
    String? id, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    List<_i11.MultipartFile>? files = const [],
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [id],
              {
                #body: body,
                #query: query,
                #files: files,
                #headers: headers,
                #expand: expand,
                #fields: fields,
              },
            ),
            returnValue: _i14.Future<_i16.RecordModel>.value(
              _FakeRecordModel_15(
                this,
                Invocation.method(
                  #update,
                  [id],
                  {
                    #body: body,
                    #query: query,
                    #files: files,
                    #headers: headers,
                    #expand: expand,
                    #fields: fields,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i16.RecordModel>);

  @override
  _i14.Future<void> delete(
    String? id, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [id],
              {#body: body, #query: query, #headers: headers},
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i17.AuthMethodsList> listAuthMethods({
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listAuthMethods, [], {
              #fields: fields,
              #query: query,
              #headers: headers,
            }),
            returnValue: _i14.Future<_i17.AuthMethodsList>.value(
              _FakeAuthMethodsList_16(
                this,
                Invocation.method(#listAuthMethods, [], {
                  #fields: fields,
                  #query: query,
                  #headers: headers,
                }),
              ),
            ),
          )
          as _i14.Future<_i17.AuthMethodsList>);

  @override
  _i14.Future<_i18.RecordAuth> authWithPassword(
    String? usernameOrEmail,
    String? password, {
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #authWithPassword,
              [usernameOrEmail, password],
              {
                #expand: expand,
                #fields: fields,
                #body: body,
                #query: query,
                #headers: headers,
              },
            ),
            returnValue: _i14.Future<_i18.RecordAuth>.value(
              _FakeRecordAuth_17(
                this,
                Invocation.method(
                  #authWithPassword,
                  [usernameOrEmail, password],
                  {
                    #expand: expand,
                    #fields: fields,
                    #body: body,
                    #query: query,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<_i18.RecordAuth> authWithOAuth2Code(
    String? provider,
    String? code,
    String? codeVerifier,
    String? redirectURL, {
    Map<String, dynamic>? createData = const {},
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #authWithOAuth2Code,
              [provider, code, codeVerifier, redirectURL],
              {
                #createData: createData,
                #body: body,
                #query: query,
                #headers: headers,
                #expand: expand,
                #fields: fields,
              },
            ),
            returnValue: _i14.Future<_i18.RecordAuth>.value(
              _FakeRecordAuth_17(
                this,
                Invocation.method(
                  #authWithOAuth2Code,
                  [provider, code, codeVerifier, redirectURL],
                  {
                    #createData: createData,
                    #body: body,
                    #query: query,
                    #headers: headers,
                    #expand: expand,
                    #fields: fields,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<_i18.RecordAuth> authWithOAuth2(
    String? providerName,
    _i12.OAuth2URLCallbackFunc? urlCallback, {
    List<String>? scopes = const [],
    Map<String, dynamic>? createData = const {},
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #authWithOAuth2,
              [providerName, urlCallback],
              {
                #scopes: scopes,
                #createData: createData,
                #body: body,
                #query: query,
                #headers: headers,
                #expand: expand,
                #fields: fields,
              },
            ),
            returnValue: _i14.Future<_i18.RecordAuth>.value(
              _FakeRecordAuth_17(
                this,
                Invocation.method(
                  #authWithOAuth2,
                  [providerName, urlCallback],
                  {
                    #scopes: scopes,
                    #createData: createData,
                    #body: body,
                    #query: query,
                    #headers: headers,
                    #expand: expand,
                    #fields: fields,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<_i18.RecordAuth> authRefresh({
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authRefresh, [], {
              #expand: expand,
              #fields: fields,
              #body: body,
              #query: query,
              #headers: headers,
            }),
            returnValue: _i14.Future<_i18.RecordAuth>.value(
              _FakeRecordAuth_17(
                this,
                Invocation.method(#authRefresh, [], {
                  #expand: expand,
                  #fields: fields,
                  #body: body,
                  #query: query,
                  #headers: headers,
                }),
              ),
            ),
          )
          as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<void> requestPasswordReset(
    String? email, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestPasswordReset,
              [email],
              {#body: body, #query: query, #headers: headers},
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> confirmPasswordReset(
    String? passwordResetToken,
    String? password,
    String? passwordConfirm, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmPasswordReset,
              [passwordResetToken, password, passwordConfirm],
              {#body: body, #query: query, #headers: headers},
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> requestVerification(
    String? email, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestVerification,
              [email],
              {#body: body, #query: query, #headers: headers},
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> confirmVerification(
    String? verificationToken, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmVerification,
              [verificationToken],
              {#body: body, #query: query, #headers: headers},
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> requestEmailChange(
    String? newEmail, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestEmailChange,
              [newEmail],
              {#body: body, #query: query, #headers: headers},
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> confirmEmailChange(
    String? emailChangeToken,
    String? userPassword, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmEmailChange,
              [emailChangeToken, userPassword],
              {#body: body, #query: query, #headers: headers},
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i19.OTPResponse> requestOTP(
    String? email, {
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestOTP,
              [email],
              {#body: body, #query: query, #headers: headers},
            ),
            returnValue: _i14.Future<_i19.OTPResponse>.value(
              _FakeOTPResponse_18(
                this,
                Invocation.method(
                  #requestOTP,
                  [email],
                  {#body: body, #query: query, #headers: headers},
                ),
              ),
            ),
          )
          as _i14.Future<_i19.OTPResponse>);

  @override
  _i14.Future<_i18.RecordAuth> authWithOTP(
    String? otpId,
    String? password, {
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #authWithOTP,
              [otpId, password],
              {
                #expand: expand,
                #fields: fields,
                #body: body,
                #query: query,
                #headers: headers,
              },
            ),
            returnValue: _i14.Future<_i18.RecordAuth>.value(
              _FakeRecordAuth_17(
                this,
                Invocation.method(
                  #authWithOTP,
                  [otpId, password],
                  {
                    #expand: expand,
                    #fields: fields,
                    #body: body,
                    #query: query,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i18.RecordAuth>);

  @override
  _i14.Future<_i15.PocketBase> impersonate(
    String? recordId,
    num? duration, {
    String? expand,
    String? fields,
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #impersonate,
              [recordId, duration],
              {
                #expand: expand,
                #fields: fields,
                #body: body,
                #query: query,
                #headers: headers,
              },
            ),
            returnValue: _i14.Future<_i15.PocketBase>.value(
              _FakePocketBase_14(
                this,
                Invocation.method(
                  #impersonate,
                  [recordId, duration],
                  {
                    #expand: expand,
                    #fields: fields,
                    #body: body,
                    #query: query,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i15.PocketBase>);

  @override
  _i14.Future<List<_i16.RecordModel>> getFullList({
    int? batch = 500,
    String? expand,
    String? filter,
    String? sort,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFullList, [], {
              #batch: batch,
              #expand: expand,
              #filter: filter,
              #sort: sort,
              #fields: fields,
              #query: query,
              #headers: headers,
            }),
            returnValue: _i14.Future<List<_i16.RecordModel>>.value(
              <_i16.RecordModel>[],
            ),
          )
          as _i14.Future<List<_i16.RecordModel>>);

  @override
  _i14.Future<_i21.ResultList<_i16.RecordModel>> getList({
    int? page = 1,
    int? perPage = 30,
    bool? skipTotal = false,
    String? expand,
    String? filter,
    String? sort,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getList, [], {
              #page: page,
              #perPage: perPage,
              #skipTotal: skipTotal,
              #expand: expand,
              #filter: filter,
              #sort: sort,
              #fields: fields,
              #query: query,
              #headers: headers,
            }),
            returnValue: _i14.Future<_i21.ResultList<_i16.RecordModel>>.value(
              _FakeResultList_19<_i16.RecordModel>(
                this,
                Invocation.method(#getList, [], {
                  #page: page,
                  #perPage: perPage,
                  #skipTotal: skipTotal,
                  #expand: expand,
                  #filter: filter,
                  #sort: sort,
                  #fields: fields,
                  #query: query,
                  #headers: headers,
                }),
              ),
            ),
          )
          as _i14.Future<_i21.ResultList<_i16.RecordModel>>);

  @override
  _i14.Future<_i16.RecordModel> getOne(
    String? id, {
    String? expand,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getOne,
              [id],
              {
                #expand: expand,
                #fields: fields,
                #query: query,
                #headers: headers,
              },
            ),
            returnValue: _i14.Future<_i16.RecordModel>.value(
              _FakeRecordModel_15(
                this,
                Invocation.method(
                  #getOne,
                  [id],
                  {
                    #expand: expand,
                    #fields: fields,
                    #query: query,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i16.RecordModel>);

  @override
  _i14.Future<_i16.RecordModel> getFirstListItem(
    String? filter, {
    String? expand,
    String? fields,
    Map<String, dynamic>? query = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFirstListItem,
              [filter],
              {
                #expand: expand,
                #fields: fields,
                #query: query,
                #headers: headers,
              },
            ),
            returnValue: _i14.Future<_i16.RecordModel>.value(
              _FakeRecordModel_15(
                this,
                Invocation.method(
                  #getFirstListItem,
                  [filter],
                  {
                    #expand: expand,
                    #fields: fields,
                    #query: query,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i16.RecordModel>);

  @override
  _i14.Future<_i16.RecordModel> create({
    Map<String, dynamic>? body = const {},
    Map<String, dynamic>? query = const {},
    List<_i11.MultipartFile>? files = const [],
    Map<String, String>? headers = const {},
    String? expand,
    String? fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #body: body,
              #query: query,
              #files: files,
              #headers: headers,
              #expand: expand,
              #fields: fields,
            }),
            returnValue: _i14.Future<_i16.RecordModel>.value(
              _FakeRecordModel_15(
                this,
                Invocation.method(#create, [], {
                  #body: body,
                  #query: query,
                  #files: files,
                  #headers: headers,
                  #expand: expand,
                  #fields: fields,
                }),
              ),
            ),
          )
          as _i14.Future<_i16.RecordModel>);
}

/// A class which mocks [RecordModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordModel extends _i1.Mock implements _i16.RecordModel {
  MockRecordModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  set data(Map<String, dynamic>? _data) => super.noSuchMethod(
    Invocation.setter(#data, _data),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, List<_i16.RecordModel>> get expand =>
      (super.noSuchMethod(
            Invocation.getter(#expand),
            returnValue: <String, List<_i16.RecordModel>>{},
          )
          as Map<String, List<_i16.RecordModel>>);

  @override
  set expand(Map<String, List<_i16.RecordModel>>? _expand) =>
      super.noSuchMethod(
        Invocation.setter(#expand, _expand),
        returnValueForMissingStub: null,
      );

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i22.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  set id(String? val) => super.noSuchMethod(
    Invocation.setter(#id, val),
    returnValueForMissingStub: null,
  );

  @override
  String get collectionId =>
      (super.noSuchMethod(
            Invocation.getter(#collectionId),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#collectionId),
            ),
          )
          as String);

  @override
  String get collectionName =>
      (super.noSuchMethod(
            Invocation.getter(#collectionName),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
          )
          as String);

  @override
  String get created =>
      (super.noSuchMethod(
            Invocation.getter(#created),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#created),
            ),
          )
          as String);

  @override
  String get updated =>
      (super.noSuchMethod(
            Invocation.getter(#updated),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#updated),
            ),
          )
          as String);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  T get<T>(String? fieldNameOrPath, [T? defaultValue]) =>
      (super.noSuchMethod(
            Invocation.method(#get, [fieldNameOrPath, defaultValue]),
            returnValue: _i22.dummyValue<T>(
              this,
              Invocation.method(#get, [fieldNameOrPath, defaultValue]),
            ),
          )
          as T);

  @override
  void set(String? fieldName, dynamic value) => super.noSuchMethod(
    Invocation.method(#set, [fieldName, value]),
    returnValueForMissingStub: null,
  );

  @override
  T getDataValue<T>(String? fieldNameOrPath, [T? defaultValue]) =>
      (super.noSuchMethod(
            Invocation.method(#getDataValue, [fieldNameOrPath, defaultValue]),
            returnValue: _i22.dummyValue<T>(
              this,
              Invocation.method(#getDataValue, [fieldNameOrPath, defaultValue]),
            ),
          )
          as T);

  @override
  String getStringValue(String? fieldNameOrPath, [String? defaultValue]) =>
      (super.noSuchMethod(
            Invocation.method(#getStringValue, [fieldNameOrPath, defaultValue]),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.method(#getStringValue, [
                fieldNameOrPath,
                defaultValue,
              ]),
            ),
          )
          as String);

  @override
  List<T> getListValue<T>(String? fieldNameOrPath, [List<T>? defaultValue]) =>
      (super.noSuchMethod(
            Invocation.method(#getListValue, [fieldNameOrPath, defaultValue]),
            returnValue: <T>[],
          )
          as List<T>);

  @override
  bool getBoolValue(String? fieldNameOrPath, [bool? defaultValue]) =>
      (super.noSuchMethod(
            Invocation.method(#getBoolValue, [fieldNameOrPath, defaultValue]),
            returnValue: false,
          )
          as bool);

  @override
  int getIntValue(String? fieldNameOrPath, [int? defaultValue]) =>
      (super.noSuchMethod(
            Invocation.method(#getIntValue, [fieldNameOrPath, defaultValue]),
            returnValue: 0,
          )
          as int);

  @override
  double getDoubleValue(String? fieldNameOrPath, [double? defaultValue]) =>
      (super.noSuchMethod(
            Invocation.method(#getDoubleValue, [fieldNameOrPath, defaultValue]),
            returnValue: 0.0,
          )
          as double);
}

/// A class which mocks [ResultList].
///
/// See the documentation for Mockito's code generation for more information.
class MockResultList<M extends _i20.Jsonable> extends _i1.Mock
    implements _i21.ResultList<M> {
  MockResultList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get page =>
      (super.noSuchMethod(Invocation.getter(#page), returnValue: 0) as int);

  @override
  set page(int? _page) => super.noSuchMethod(
    Invocation.setter(#page, _page),
    returnValueForMissingStub: null,
  );

  @override
  int get perPage =>
      (super.noSuchMethod(Invocation.getter(#perPage), returnValue: 0) as int);

  @override
  set perPage(int? _perPage) => super.noSuchMethod(
    Invocation.setter(#perPage, _perPage),
    returnValueForMissingStub: null,
  );

  @override
  int get totalItems =>
      (super.noSuchMethod(Invocation.getter(#totalItems), returnValue: 0)
          as int);

  @override
  set totalItems(int? _totalItems) => super.noSuchMethod(
    Invocation.setter(#totalItems, _totalItems),
    returnValueForMissingStub: null,
  );

  @override
  int get totalPages =>
      (super.noSuchMethod(Invocation.getter(#totalPages), returnValue: 0)
          as int);

  @override
  set totalPages(int? _totalPages) => super.noSuchMethod(
    Invocation.setter(#totalPages, _totalPages),
    returnValueForMissingStub: null,
  );

  @override
  List<M> get items =>
      (super.noSuchMethod(Invocation.getter(#items), returnValue: <M>[])
          as List<M>);

  @override
  set items(List<M>? _items) => super.noSuchMethod(
    Invocation.setter(#items, _items),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
